INSERT INTO [dbo].[Livro] (Titulo, Editora, Edicao, AnoPublicacao, DataCriacao) VALUES 
('Cem Anos de Solidão', 'Editora Realismo Mágico', 1, '1967', GETDATE()),
('Harry Potter e a Pedra Filosofal', 'Editora Fantasia', 1, '1997', GETDATE()),
('1984', 'Editora Distopia', 1, '1949', GETDATE()),
('Orgulho e Preconceito', 'Editora Romance Histórico', 1, '1813', GETDATE()),
('O Velho e o Mar', 'Editora Clássicos', 1, '1952', GETDATE()),
('As Aventuras de Tom Sawyer', 'Editora Aventura', 1, '1876', GETDATE()),
('Guerra e Paz', 'Editora Filosofia', 1, '1869', GETDATE()),
('A Metamorfose', 'Editora Surrealismo', 1, '1915', GETDATE()),
('Crime e Castigo', 'Editora Psicologia', 1, '1866', GETDATE()),
('Mrs. Dalloway', 'Editora Modernismo', 1, '1925', GETDATE()),
('Grandes Esperanças', 'Editora Crítica Social', 1, '1861', GETDATE()),
('O Morro dos Ventos Uivantes', 'Editora Tragédia', 1, '1847', GETDATE()),
('Moby Dick', 'Editora Marinha', 1, '1851', GETDATE()),
('O Retrato de Dorian Gray', 'Editora Teatro', 1, '1890', GETDATE()),
('O Senhor dos Anéis', 'Editora Fantasia Épica', 1, '1954', GETDATE()),
('Norwegian Wood', 'Editora Existencialismo', 1, '1987', GETDATE()),
('A Casa dos Espíritos', 'Editora Realismo Mágico', 1, '1982', GETDATE()),
('Dom Quixote', 'Editora Clássicos', 1, '1605', GETDATE()),
('Romeu e Julieta', 'Editora Poesia', 1, '1597', GETDATE()),
('Sherlock Holmes: Um Estudo em Vermelho', 'Editora Mistério', 1, '1887', GETDATE());
