INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Filosofia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Matemática', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('História', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Física', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Biologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Química', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Ciência da Computação', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Engenharia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Economia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Psicologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Direito', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Medicina', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Geografia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Astronomia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Ficção Científica', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Romance', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Poesia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Arte', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Música', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Cinema', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Fotografia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Arquitetura', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Negócios', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Administração', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Marketing', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Finanças', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Religião', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Espiritualidade', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Esportes', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Saúde', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Nutrição', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Educação', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Linguística', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Literatura', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Antropologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Sociologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Política', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('História Natural', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Geologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Zoologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Botânica', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Tecnologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Inteligência Artificial', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Machine Learning', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Segurança da Informação', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Criptografia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Blockchain', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Realidade Virtual', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Realidade Aumentada', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Big Data', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Ciência de Dados', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Cultura', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Jornalismo', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Lógica', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Ética', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Estatística', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Probabilidade', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('História da Arte', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Teoria da Música', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Teoria Literária', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Psicanálise', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Ecologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Meteorologia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Oceanografia', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Literatura Infantil', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Literatura Juvenil', GETDATE());
INSERT INTO [dbo].[Assunto] (Descricao, DataCriacao) VALUES ('Biografia', GETDATE());
