INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Gabriel García Márquez', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('J.K. Rowling', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('George Orwell', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Jane Austen', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Ernest Hemingway', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Mark Twain', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Leo Tolstoy', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Franz Kafka', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Fyodor Dostoevsky', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Virginia Woolf', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Charles Dickens', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Emily Brontë', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Herman Melville', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Oscar Wilde', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('J.R.R. Tolkien', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Haruki Murakami', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Isabel Allende', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Miguel de Cervantes', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('William Shakespeare', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Arthur Conan Doyle', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Stephen King', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Agatha Christie', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Dan Brown', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('John Steinbeck', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Jack London', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Chimamanda Ngozi Adichie', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Toni Morrison', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Kurt Vonnegut', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Ray Bradbury', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Margaret Atwood', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Philip K. Dick', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Douglas Adams', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('H.G. Wells', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Isaac Asimov', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Aldous Huxley', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('James Joyce', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Zadie Smith', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Orhan Pamuk', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Gabriela Mistral', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Jorge Luis Borges', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Gabriel García Márquez', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Pablo Neruda', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Mario Vargas Llosa', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Carlos Fuentes', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('José Saramago', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Umberto Eco', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Italo Calvino', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Elena Ferrante', GETDATE());
INSERT INTO [dbo].[Autor] (Nome, DataCriacao) VALUES ('Cecília Meireles', GETDATE());
